version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: employee_sql
    environment:
      SA_PASSWORD: "StrongPassword!123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "StrongPassword!123"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: employee_api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EmployeeDb;User Id=sa;Password=StrongPassword!123;TrustServerCertificate=True"
    ports:
      - "8080:8080"
    command: ["dotnet", "Api.dll"]

volumes:
  sql_data:
